import './globals.css'
import { Montserrat } from "@next/font/google"

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--font-monserrat"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`{$monserrat.className} mx-32 my-12`} >
        {children}
        </body>
    </html>
  )
}
